# Resolution settings.
# Can adjust this to 1024 for image training, especially on 24gb cards.
resolutions = [512]

# Aspect ratio bucketing settings
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7

# Frame buckets images only
#frame_buckets = [1]

# Mix of images and videos (at 33 and 60 frames long)
frame_buckets = [33]

[[directory]]
# Set this to where your dataset is
path = '/dataset/Spanking'
# Reduce as necessary
num_repeats = 5